### ISSUE TITLE
Strange char in " ;  " place.

### ISSUE THREAD

**Issue by renancunha33** [arthur393/MTM2015#1]
Please, change the char below to <b>" ; "</b> :<h1>
؛
</h1><br />
This char could cause problems for the users that can use code to study.

Thanks for read it! :+1:

**Comment by arthur393** [comment]
Thank to report this 'problem' with a strange char.

But if a "user" use some features of text editors, like Ctrl+H, he will change all the strange to the right...

FYI, this code is not to study using, it is just to compile on a MTM in a IBM Mainframe.

**Comment by renancunha33** [comment]
but this can harm someone that see the code. If it is not to study you need to make a private repository.
